gantt
title The Path
    section 2021-2031
    EM :, 2021-05-01, 52w
    Further training @ Nominet :milestone, 2022-04-01, 0d
    DoE :, 2022-05-01, 104w
    Multiple teams delivering SaaS :milestone, 2024-04-01, 0d
    Win an award :milestone, 2023-04-01, 0d
    HoE :, 2024-05-01, 500w
    Demonstrate a lifetime of success :milestone, 2030-04-01, 0d
    CTO :, 2033-05-01, 500w
