sequenceDiagram
participant PastAlice
participant Bob
PastAlice->>John: Hello John, how are you?
loop Healthcheck
John->>John: Fight against hypochondria
end
Note right of John: Rational thoughts <br/>prevail!
John-->>PastAlice: Great!
John->>Bob: How about you?
Bob-->>John: Jolly good!
